### ISSUE TITLE
Help making a label with a "title" and "description

### ISSUE THREAD

**Issue by W-M-D** [Edinburgh-Genome-Foundry/blabel#14]
I've tried using "<\h1>" or changing the type in CSS but nothing seems to work. I just want two different text elements that have different sizes. Any one know what to do ?

**Comment by veghp** [comment]
Hi, the span tag works for me:

Template:
```html
<div><span class='small'> Small text </span><br></div>
<span class='big'> Made with blabel <br></span>
```
CSS
```CSS
.small {
  font-family: Verdana;
  font-weight: bold;
  vertical-align: middle;
  display: inline-block;
  font-size: 10px;
}
.big {
  font-family: Verdana;
  font-weight: bold;
  vertical-align: middle;
  display: inline-block;
  font-size: 30px;
```
[example.pdf](https://github.com/Edinburgh-Genome-Foundry/blabel/files/7294168/example.pdf)

Also works with the div element:
```CSS
#small_text
{
    font-size: 10px;
    margin-bottom: 0.2mm;
    width: 25mm;
}
```
