### ISSUE TITLE
How to create multiline label with name at the bottom

### ISSUE THREAD

**Issue by noppGithub** [Edinburgh-Genome-Foundry/blabel#5]
I want to create labels with the following contents.
Is it possible to do ?
```python
52/3 Avenue road,
Chumpo district,
Lamgo province 19456
                                          <John Saverilo>
```

**Comment by veghp** [comment]
There are many ways to do it; for example edit `style.css` to resize label and add "right" class:
```css
@page {
    width: 35mm;
    height: 11mm;
    padding: 0.5mm;
}
img {
    height: 6.4mm;
    display: inline-block;
    vertical-align: middle;
    image-rendering: pixelated;
}
.label {
    font-family: Ubuntu;
    font-weight: bold;
    vertical-align: middle;
    display: inline-block;
    font-size: 7px;
}
.right{
    float:right;
}

```
And the template html:
```html
<img src="{{label_tools.qr_code(sample_id)}}"/>
<span class='label'>
    {{ sample_name }} <br/>
    52/3 Avenue road, <br/>
    Chumpo district, <br/>
    Lamgo province 19456 <br/>
    <span class="right">&lt;John Saverilo&gt;</span>
</span>
```
![label](https://user-images.githubusercontent.com/31794642/97802063-e2939080-1c38-11eb-92fc-bb5445510f64.jpg)

For more customization, see the online documentations on html and css.

**Comment by noppGithub** [comment]
@veghp 

Thank you so much for the prompt response, your solution is working.
But I still need to add 2 options.
- Change the font to my local TTF, OTF file
- Put all of the labels in a single A4 page.

My current code is below, and the current result is attached, I want to put all the labels in a single A4 page(s)
Files:
- [Excel file input](https://github.com/noppGithub/_public-share/blob/master/blabel/file.xlsx)
- [PDF output file](https://github.com/noppGithub/_public-share/blob/master/blabel/labels_from_spreadsheet.pdf)

**my_blabel.py**
```python
from blabel import LabelWriter
import pandas

df = pandas.read_excel("file.xlsx")
df = df.iloc[:100,:]
records = df.to_dict(orient="records")

label_writer = LabelWriter("item_template.html", default_stylesheets=("style.css",))

label_writer.write_labels(records, target="labels_from_spreadsheet.pdf")
```
**style.css**
```css
@page {
    width: 297mm;
    height: 420mm;
    padding: 4.5mm;
}
img {
    height: 6.4mm;
    display: inline-block;
    vertical-align: middle;
    image-rendering: pixelated;
}
.label {
    font-family: Ubuntu;
    font-weight: bold;
    vertical-align: middle;
    display: inline-block;
    font-size: 7px;
}
.right{
    float:right;
}
```

**item_template.html**
```html
<span class='label'>
    {{ FIRST_NAME }} {{ SURNAME }} <br/>
    {{ ADDLINE1 }}, <br/>
    {{ ADDLINE2 }}, <br/>
    {{ ADDLINE3 }} {{ ZIPCODE }} <br/>
    <span class="right">&lt;{{ ID_NUM }}&gt;</span>
</span>
```
